/* generated configuration header file - do not edit */
#ifndef R_POEG_CFG_H_
#define R_POEG_CFG_H_
#define POEG_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define POEG_CFG_MULTIPLEX_INTERRUPT_SUPPORTED (0)
#if POEG_CFG_MULTIPLEX_INTERRUPT_SUPPORTED
 #define POEG_CFG_MULTIPLEX_INTERRUPT_ENABLE        BSP_INTERRUPT_ENABLE
 #define POEG_CFG_MULTIPLEX_INTERRUPT_DISABLE       BSP_INTERRUPT_DISABLE
#else
#define POEG_CFG_MULTIPLEX_INTERRUPT_ENABLE
#define POEG_CFG_MULTIPLEX_INTERRUPT_DISABLE
#endif
#endif /* R_POEG_CFG_H_ */
