#include "hal_data.h"
#include "sio_char.h"
#include <stdio.h>
#include "m_common.h"
#include "r_cg_macrodriver.h"


FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

void handle_error (fsp_err_t err);
void user_uart_callback (uart_callback_args_t * p_args);

uint8_t  g_out_of_band_received[TRANSFER_LENGTH];
volatile uint32_t g_transfer_complete = 0;
volatile uint32_t g_receive_complete  = 0;
uint32_t g_out_of_band_index = 0;

#define CHARACTER_LENGTH_BYTE   (20)
uint8_t rx_buffer[RX_BUF_SIZE];  // 静态分配接收缓冲区
volatile uint32_t g_rx_count = 0;

char gbuff[16];
uint8_t tx_buffer[] = "Hello,this is rs232(uart4) test\n";
extern void R_Systeminit(void);

static void calc_cmd_vel64(t_motor *pm)
{
    long long temp;

    temp = (long long)pm->cmd_vel_rpm * VEL_BASE_DIG_NUM * pm->crnt_ds;
    pm->cmd_vel64 = (((temp * pm->ec_per_rev) / CNVGAIN_RPS_TO_RPM) / CNVGAIN_SEC_TO_POS_LP_CYC);
    pm->in_vel64 = pm->cmd_vel64;
}
/*******************************************************************************************************************//**
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{

    R_RWP_NS->PRCRN = 0x0000A50F; //PRCRN register
    R_RWP_S->PRCRS = 0x0000A50F; //PRCRS register
    R_SYSC_NS->MSTPCRA_b.MSTPCRA00 &= 0xFFFFFFFE; //MSTPCRA register Bit0 Clear
    R_SYSC_NS->MSTPCRC_b.MSTPCRC05=0; //MSTPCRC register Bit5(TFU) Clear
    R_Systeminit();
    m_startup();

#if   defined(__ICCARM__)
    __disable_interrupt();
#elif defined(__GNUC__)
    DI();
#endif
    asm volatile("isb");                  // Ensuring data-changing

#if   defined(__ICCARM__)
   __enable_interrupt();
#elif defined(__GNUC__)
   EI();
#endif

    asm volatile("isb"); // Ensuring data-changing
//printf("motor test\n");
    extern t_motor g_st_m[MOTOR_NUM];
       if(SW12_4 == 1) /* SW12_4 : OFF */
       {
           while (1)
           {
               m_foreground();
           }
       }
       else if(SW12_4 == 0) /* SW12_4 : ON */
       {
#if 1
           for(uint32_t idx = 0; idx < MOTOR_NUM; idx++)
           {
               switch (idx)
               {
                   case 2:
                   case 3:
                   case 6:
                   case 7:
                   case 8:
                       map_phases(&g_st_m[idx]);
                       set_cmt_params(&g_st_m[idx]);
                   /* Servo Off */
                       g_st_m[idx].vel_error = 0;
                       g_st_m[idx].integral_err_vel = 0;
                       g_st_m[idx].derivative_err_vel = 0;
                       g_st_m[idx].vel_error2 = 0;
                       g_st_m[idx].integral_err2_vel = 0;
                       g_st_m[idx].derivative_err2_vel = 0;
                       g_st_m[idx].foc_id_err_old = 0;
                       g_st_m[idx].foc_iq_err_old = 0;
                       g_st_m[idx].pos_loop_cmd = 0;
                       g_st_m[idx].output_q = 0;
                       g_st_m[idx].output_d = 0;
                       g_st_m[idx].output_q_old = g_st_m[idx].output_q;
                       g_st_m[idx].output_d_old = g_st_m[idx].output_d;
                       g_st_m[idx].crnt_kp_vel = INITVAL_VEL_KP;
                       g_st_m[idx].crnt_ki_vel = INITVAL_VEL_KI;
                       g_st_m[idx].integral_limit_vel = INITVAL_VEL_ILIMIT;
                       g_st_m[idx].PiOut_limit_vel    = INITVAL_VEL_MLIMIT;
                       g_st_m[idx].act_state |= ACT_PowerOn;
                       g_st_m[idx].act_state &= ~(ACT_AmpFault | ACT_PosError | ACT_WrapAround | ACT_OverCurrent | ACT_Inhibit | ACT_PVTEmpty);
                       g_st_m[idx].vpg_state = VPG_MotionCompleted;
                       g_st_m[idx].ctrl_mode = CTRM_VELOCITY;
                       g_st_m[idx].aligning = 1;
                       g_st_m[idx].commutation_mode = 0;
                       break;
                   default:
                       break;
               }
           }
#endif
#if 0
           /* Run Veclocity Profile Generators */
           for(uint32_t idx = 0; idx < MOTOR_NUM; idx++)
           {
               vpg_update(&g_st_m[idx]);
           }

           /* Check recorder trigger conditions */
           m_rec_begin();
#endif
           for(uint32_t idx = 0; idx < MOTOR_NUM; idx++)
           {
               switch (idx)
               {
                    case 2:
                    case 3:
                    case 6:
                    case 7:
                    case 8:
                        pwm_enable(&g_st_m[idx]);
                        break;
                    default:
                        break;
               }
           }

           while(g_st_m[MOTOR_NUM - 1].charge_state != BS_CHARGE_END)
           {
               /* Wait */
           }

           while(g_st_m[MOTOR_NUM - 1].aligning)
           {
               /* Wait until the phasing process is completed */
           }

           R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);

           //for(uint32_t idx = 0; idx < MOTOR_NUM; idx++)
          // {
               for(uint32_t i = 0; i <= 1000; i = i + 10){
                   //g_st_m[idx].cmd_vel_rpm = -i; // [rpm]
                   //calc_cmd_vel64(&g_st_m[idx]);
                  // g_st_m[idx].servo_on = 1;
                  // g_st_m[idx].act_state &= ~(ACT_AmpFault | ACT_PosError | ACT_WrapAround | ACT_OverCurrent | ACT_Inhibit);
                   g_st_m[8].cmd_vel_rpm = -i; // [rpm]
                   g_st_m[2].cmd_vel_rpm = -i; // [rpm]
                   g_st_m[3].cmd_vel_rpm = -i; // [rpm]
                   g_st_m[6].cmd_vel_rpm = -i; // [rpm]
                   g_st_m[7].cmd_vel_rpm = -i; // [rpm]
                   calc_cmd_vel64(&g_st_m[8]);
                   calc_cmd_vel64(&g_st_m[2]);
                   calc_cmd_vel64(&g_st_m[3]);
                   calc_cmd_vel64(&g_st_m[6]);
                   calc_cmd_vel64(&g_st_m[7]);

                   g_st_m[8].servo_on = 1;
                   g_st_m[2].servo_on = 1;
                   g_st_m[3].servo_on = 1;
                   g_st_m[6].servo_on = 1;
                   g_st_m[7].servo_on = 1;
                   R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MICROSECONDS);
               }
               R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);
          // }
           while(1);
       }
       else
       {
           /* Do nothing */
       }

       while(1);

}

//#pragma type_attribute=__irq __arm
void r_gpt_interrupt(timer_callback_args_t *p_args)
{
    switch(p_args->event)
    {
    case TIMER_EVENT_TROUGH:
        m_background();
        break;
    default:
        break;
    }
}


void user_uart_callback (uart_callback_args_t * p_args)
{
    /* Handle the UART event */
    switch (p_args->event)
    {
        /* Received a character */
        case UART_EVENT_RX_CHAR:
        {
            /* Only put the next character in the receive buffer if there is space for it */
            if (sizeof(g_out_of_band_received) > g_out_of_band_index)
            {
                /* Write either the next one or two bytes depending on the receive data size */
                if ((UART_DATA_BITS_7 == g_uart0_cfg.data_bits) || (UART_DATA_BITS_8 == g_uart0_cfg.data_bits))
                {
                    g_out_of_band_received[g_out_of_band_index++] = (uint8_t) p_args->data;
                }
                else
                {
                    uint16_t * p_dest = (uint16_t *) &g_out_of_band_received[g_out_of_band_index];
                    *p_dest              = (uint16_t) p_args->data;
                    g_out_of_band_index += 2;
                }
            }
            break;
        }
        /* Receive complete */
        case UART_EVENT_RX_COMPLETE:
        {
            g_receive_complete = 1;
            g_rx_count = g_out_of_band_index;
            //printf("rx_count=%d\n",g_rx_count);
            break;
        }
        /* Transmit complete */
        case UART_EVENT_TX_COMPLETE:
        {
            g_transfer_complete = 1;
            break;
        }
        default:
        {
        }
    }
}


void handle_error (fsp_err_t err)
{
    FSP_PARAMETER_NOT_USED(err);
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }
    }
}
