/* generated ELC source file - do not edit */
#include "r_elc_api.h"
#include "common_data.h"
const elc_cfg_t g_elc_cfg =
{ .link[ELC_PERIPHERAL_MTU0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_MTU3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_MTU4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT00_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT00_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT00_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT00_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT00_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT00_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT01_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT01_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT01_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT01_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT01_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT01_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT02_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT02_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT02_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT02_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT02_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT02_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT03_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT03_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT03_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT03_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT03_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT03_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT04_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT04_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT04_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT04_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT04_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT04_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT05_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT05_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT05_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT05_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT05_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT05_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT06_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT06_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT06_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT06_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT06_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT06_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT07_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT07_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT07_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT07_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT07_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT07_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT08_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT08_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT08_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT08_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT08_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT08_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT09_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT09_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT09_C] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT09_D] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT09_E] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT09_F] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT09_G] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GPT09_H] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC0_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC0_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC1_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC1_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC2_A] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ADC2_B] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP0] = ELC_EVENT_GPT00_0_ADTRGA, /* GPT00_0_ADTRGA (GPT00_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF0_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CDCNT0] = ELC_EVENT_GPT00_0_ADTRGA, /* GPT00_0_ADTRGA (GPT00_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF0_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF0_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP0] = ELC_EVENT_GPT01_0_ADTRGA, /* GPT01_0_ADTRGA (GPT01_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF1_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CDCNT0] = ELC_EVENT_GPT01_0_ADTRGA, /* GPT01_0_ADTRGA (GPT01_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF1_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF1_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF2_CAP0] = ELC_EVENT_GPT02_0_ADTRGA, /* GPT02_0_ADTRGA (GPT02_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF2_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF2_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF2_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF2_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF2_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF2_CDCNT0] = ELC_EVENT_GPT02_0_ADTRGA, /* GPT02_0_ADTRGA (GPT02_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF2_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF2_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF3_CAP0] = ELC_EVENT_GPT03_0_ADTRGA, /* GPT03_0_ADTRGA (GPT03_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF3_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF3_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF3_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF3_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF3_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF3_CDCNT0] = ELC_EVENT_GPT03_0_ADTRGA, /* GPT03_0_ADTRGA (GPT03_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF3_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF3_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF4_CAP0] = ELC_EVENT_GPT04_0_ADTRGA, /* GPT04_0_ADTRGA (GPT04_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF4_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF4_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF4_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF4_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF4_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF4_CDCNT0] = ELC_EVENT_GPT04_0_ADTRGA, /* GPT04_0_ADTRGA (GPT04_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF4_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF4_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF5_CAP0] = ELC_EVENT_GPT05_0_ADTRGA, /* GPT05_0_ADTRGA (GPT05_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF5_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF5_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF5_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF5_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF5_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF5_CDCNT0] = ELC_EVENT_GPT05_0_ADTRGA, /* GPT05_0_ADTRGA (GPT05_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF5_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF5_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF6_CAP0] = ELC_EVENT_GPT06_0_ADTRGA, /* GPT06_0_ADTRGA (GPT06_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF6_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF6_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF6_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF6_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF6_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF6_CDCNT0] = ELC_EVENT_GPT06_0_ADTRGA, /* GPT06_0_ADTRGA (GPT06_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF6_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF6_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF7_CAP0] = ELC_EVENT_GPT07_0_ADTRGA, /* GPT07_0_ADTRGA (GPT07_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF7_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF7_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF7_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF7_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF7_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF7_CDCNT0] = ELC_EVENT_GPT07_0_ADTRGA, /* GPT07_0_ADTRGA (GPT07_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF7_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF7_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF8_CAP0] = ELC_EVENT_GPT08_0_ADTRGA, /* GPT08_0_ADTRGA (GPT08_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF8_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF8_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF8_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF8_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF8_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF8_CDCNT0] = ELC_EVENT_GPT08_0_ADTRGA, /* GPT08_0_ADTRGA (GPT08_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF8_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF8_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF9_CAP0] = ELC_EVENT_GPT00_0_ADTRGA, /* GPT00_0_ADTRGA (GPT00_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF9_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF9_CAP2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF9_CAP3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF9_CAP4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF9_CAP5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF9_CDCNT0] = ELC_EVENT_GPT00_0_ADTRGA, /* GPT00_0_ADTRGA (GPT00_0 GTADTRA compare match (A/D Converter Start Request A)) */
  .link[ELC_PERIPHERAL_DSMIF9_CDCNT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_DSMIF9_CDCNT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG4] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG5] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG6] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG7] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG8] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG9] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG10] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG11] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG12] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG13] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG14] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCIF_SS_TRG15] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ESC0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ESC1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GMAC0_CAP0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GMAC0_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GMAC1_CAP0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GMAC1_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GMAC2_CAP0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_GMAC2_CAP1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_OUTPORTGR1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_OUTPORTGR2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_INPORTGR1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_INPORTGR2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_SINGLEPORT0] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_SINGLEPORT1] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_SINGLEPORT2] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_SINGLEPORT3] = ELC_EVENT_NONE, /* No allocation */
  .link[ELC_PERIPHERAL_ENCOUT_TRIGGER] = ELC_EVENT_NONE, /* No allocation */
#ifdef ELC_CFG_EXTEND_SUPPORTED
            .p_extend = (void const*)&elc_cfg_extend,
        #else
  .p_extend = (void const*) NULL,
#endif
        };
